package RapidTest::Model::DB;
use Moo;
extends 'Catalyst::Model::DBIC::Schema';

use strict;
use warnings;



__PACKAGE__->config(
    schema_class => 'RapidTest::DB',
    
    connect_info => {
       dsn => 'dbi:mysql:database=RapidTest',
       user => 'root',
       password => '',
       mysql_enable_utf8 => q{1},
       mysql_auto_reconnect => q{1},
       quote_names => q{1},
    },

    # Configs for the RapidApp::RapidDbic Catalyst Plugin:
    RapidDbic => {

       # use only the relationship column of a foreign-key and hide the 
       # redundant literal column when the names are different:
       hide_fk_columns => 1,

       # grid_params are used to configure the grid module which is 
       # automatically setup for each source in the navtree
       grid_params => {
          # The special '*defaults' key applies to all sources at once
          '*defaults' => {
             include_colspec     => ['*'], #<-- default already ['*']
             ## uncomment these lines to turn on editing in all grids
             updatable_colspec   => ['*'],
             creatable_colspec   => ['*'],
             destroyable_relspec => ['*'],
          }
       },
       
       # TableSpecs define extra RapidApp-specific metadata for each source
       # and is used/available to all modules which interact with them
       TableSpecs => {
          Test => {
          },
          Test2 => {
          },
       },
    }

);



=head1 NAME

RapidTest::Model::DB - Catalyst/RapidApp DBIC Schema Model

=head1 SYNOPSIS

See L<RapidTest>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<RapidTest::DB>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema::ForRapidDbic - 0.65

=head1 AUTHOR

root

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
